// bankList.js
const bankList = [
    { code: 'ABB', name: 'Ngân hàng TMCP An Bình' },
    { code: 'ACB', name: 'Ngân hàng TMCP Á Châu' },
    { code: 'BAB', name: 'Ngân hàng TMCP Bắc Á' },
    { code: 'BIDV', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam' },
    { code: 'BVB', name: 'Ngân hàng TMCP Bảo Việt' },
    { code: 'CAKE', name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank' },
    { code: 'CBB', name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam' },
    { code: 'CIMB', name: 'Ngân hàng TNHH MTV CIMB Việt Nam' },
    { code: 'COOPBANK', name: 'Ngân hàng Hợp tác xã Việt Nam' },
    { code: 'DBS', name: 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh' },
    { code: 'DOB', name: 'Ngân hàng TMCP Đông Á' },
    { code: 'EIB', name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam' },
    { code: 'GPB', name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu' },
    { code: 'HDB', name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh' },
    { code: 'HLBVN', name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam' },
    { code: 'HSBC', name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)' },
    { code: 'IBK - HCM', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh' },
    { code: 'IBK - HN', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội' },
    { code: 'ICB', name: 'Ngân hàng TMCP Công thương Việt Nam' },
    { code: 'IVB', name: 'Ngân hàng TNHH Indovina' },
    { code: 'KBank', name: 'Ngân hàng Đại chúng TNHH Kasikornbank' },
    { code: 'KBHCM', name: 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh' },
    { code: 'KBHN', name: 'Ngân hàng Kookmin - Chi nhánh Hà Nội' },
    { code: 'KLB', name: 'Ngân hàng TMCP Kiên Long' },
    { code: 'LPB', name: 'Ngân hàng TMCP Bưu Điện Liên Việt' },
    { code: 'MB', name: 'Ngân hàng TMCP Quân đội' },
    { code: 'MSB', name: 'Ngân hàng TMCP Hàng Hải' },
    { code: 'NAB', name: 'Ngân hàng TMCP Nam Á' },
    { code: 'NCB', name: 'Ngân hàng TMCP Quốc Dân' },
    { code: 'NHB HN', name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội' },
    { code: 'OCB', name: 'Ngân hàng TMCP Phương Đông' },
    { code: 'Oceanbank', name: 'Ngân hàng Thương mại TNHH MTV Đại Dương' },
    { code: 'PBVN', name: 'Ngân hàng TNHH MTV Public Việt Nam' },
    { code: 'PGB', name: 'Ngân hàng TMCP Xăng dầu Petrolimex' },
    { code: 'PVCB', name: 'Ngân hàng TMCP Đại Chúng Việt Nam' },
    { code: 'SCB', name: 'Ngân hàng TMCP Sài Gòn' },
    { code: 'SCVN', name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam' },
    { code: 'SEAB', name: 'Ngân hàng TMCP Đông Nam Á' },
    { code: 'SGICB', name: 'Ngân hàng TMCP Sài Gòn Công Thương' },
    { code: 'SHB', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội' },
    { code: 'SHBVN', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam' },
    { code: 'STB', name: 'Ngân hàng TMCP Sài Gòn Thương Tín' },
    { code: 'TCB', name: 'Ngân hàng TMCP Kỹ thương Việt Nam' },
    { code: 'TIMO', name: 'Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)' },
    { code: 'TPB', name: 'Ngân hàng TMCP Tiên Phong' },
    { code: 'Ubank', name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank' },
    { code: 'UOB', name: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh' },
    { code: 'VAB', name: 'Ngân hàng TMCP Việt Á' },
    { code: 'VBA', name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam' },
    { code: 'VCB', name: 'Ngân hàng TMCP Ngoại Thương Việt Nam' },
    { code: 'VCCB', name: 'Ngân hàng TMCP Bản Việt' },
    { code: 'VIB', name: 'Ngân hàng TMCP Quốc tế Việt Nam' },
    { code: 'VIETBANK', name: 'Ngân hàng TMCP Việt Nam Thương Tín' },
    { code: 'VNPTMONEY', name: 'Trung tâm dịch vụ tài chính số VNPT- Chi nhánh Tổng công ty truyền thông (VNPT Fintech)' },
    { code: 'VPB', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng' },
    { code: 'VRB', name: 'Ngân hàng Liên doanh Việt - Nga' },
    { code: 'VTLMONEY', name: 'Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội' },
    { code: 'WVN', name: 'Ngân hàng TNHH MTV Woori Việt Nam' }
  ];
  
  export default bankList;
  